list_exp_llf_HN = [
    # { # default llHN
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast', 
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-00',
    #     'max_cases': 15,
    # },
    # { # llHN overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,  
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.3,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-01-overlap',
    #     'max_cases': 15,
    # },
    # { # llHN overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.4,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-02-overlap',
    #     'max_cases': 15,
    # },
    # { # llHN overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.5,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-03-overlap',
    #     'max_cases': 15,
    # },
    # { # llHN boundCT
    #     'CT_LOWER': -1000.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-04-boundCT',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-05-organ',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-06-organ',
    #     'max_cases': 15,
    # },
    # { # mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'constant',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-07-mode',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.06,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-08-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.25,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-09-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.5,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-10-sigma_scale',
    #     'max_cases': 15,
    # },
    { # padding_mode
        'CT_LOWER': -1024.0,
        'CT_UPPER': 3071.0,
        'MRI_LOWER': 0.0,
        'MRI_UPPER': 1357.0,
        'anatomical_region': 'HN',
        'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
        'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
        'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
        'mode': 'gaussian',
        'overlap': 0.2,
        'padding_mode': 'constant',
        'sampling_quality': 'fast',
        'sigma_scale': 0.125,
        'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-11-padding',
        'max_cases': 15,
    },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'replicate',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-12-padding',
    #     'max_cases': 15,
    # },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-HN/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_1.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'circular',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-HN-13-padding',
    #     'max_cases': 15,
    # },
]

# Derive u2lf HN experiments from llf HN with modified paths
list_exp_u2lf_HN = []
for _exp in list_exp_llf_HN:
    _new = _exp.copy()
    _new['checkpoint_dir'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-u2lf-HN/epoch_700'
    _new['config_path'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_2.yaml'
    if 'exp_name' in _new and isinstance(_new['exp_name'], str):
        _new['exp_name'] = _new['exp_name'].replace('/llf-HN-', '/u2lf-HN-')
    list_exp_u2lf_HN.append(_new)

list_exp_llf_AB = [
    # { # default llAB
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-00',
    #     'max_cases': 15,
    # },
    # { # llAB overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.3,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-01-overlap',
    #     'max_cases': 15,
    # },
    # { # llAB overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.4,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-02-overlap',
    #     'max_cases': 15,
    # },
    # { # llAB overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.5,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-03-overlap',
    #     'max_cases': 15,
    # },
    # { # llAB boundCT
    #     'CT_LOWER': -1000.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-04-boundCT',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-05-organ',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-06-organ',
    #     'max_cases': 15,
    # },
    # { # mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'constant',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-07-mode',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.06,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-08-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.25,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-09-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.5,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-10-sigma_scale',
    #     'max_cases': 15,
    # },
    { # padding_mode
        'CT_LOWER': -1024.0,
        'CT_UPPER': 3071.0,
        'MRI_LOWER': 0.0,
        'MRI_UPPER': 1357.0,
        'anatomical_region': 'AB',
        'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
        'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
        'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
        'mode': 'gaussian',
        'overlap': 0.2,
        'padding_mode': 'constant',
        'sampling_quality': 'fast',
        'sigma_scale': 0.125,
        'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-11-padding',
        'max_cases': 15,
    },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'replicate',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-12-padding',
    #     'max_cases': 15,
    # },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-AB/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_3.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'circular',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-AB-13-padding',
    #     'max_cases': 15,
    # },
]

# Derive u2lf AB experiments from llf AB with modified paths
list_exp_u2lf_AB = []
for _exp in list_exp_llf_AB:
    _new = _exp.copy()
    _new['checkpoint_dir'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-u2lf-AB/epoch_700'
    _new['config_path'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_4.yaml'
    if 'exp_name' in _new and isinstance(_new['exp_name'], str):
        _new['exp_name'] = _new['exp_name'].replace('/llf-AB-', '/u2lf-AB-')
    list_exp_u2lf_AB.append(_new)

list_exp_llf_TH = [
    # { # default llHN
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-00',
    #     'max_cases': 15,
    # },
    # { # llTH overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.3,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-01-overlap',
    #     'max_cases': 15,
    # },
    # { # llTH overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.4,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-02-overlap',
    #     'max_cases': 15,
    # },
    # { # llTH overlap
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.5,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-03-overlap',
    #     'max_cases': 15,
    # },
    # { # llTH boundCT
    #     'CT_LOWER': -1000.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-04-boundCT',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'AB',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/AB',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-05-organ',
    #     'max_cases': 15,
    # },
    # { # another organ
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'HN',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/HN',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-06-organ',
    #     'max_cases': 15,
    # },
    # { # mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'constant',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-07-mode',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.06,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-08-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.25,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-09-sigma_scale',
    #     'max_cases': 15,
    # },
    # { # sigma_scale
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'reflect',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.5,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-10-sigma_scale',
    #     'max_cases': 15,
    # },
    { # padding_mode
        'CT_LOWER': -1024.0,
        'CT_UPPER': 3071.0,
        'MRI_LOWER': 0.0,
        'MRI_UPPER': 1357.0,
        'anatomical_region': 'TH',
        'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
        'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
        'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
        'mode': 'gaussian',
        'overlap': 0.2,
        'padding_mode': 'constant',
        'sampling_quality': 'fast',
        'sigma_scale': 0.125,
        'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-11-padding',
        'max_cases': 15,
    },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'replicate',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-12-padding',
    #     'max_cases': 15,
    # },
    # { # padding_mode
    #     'CT_LOWER': -1024.0,
    #     'CT_UPPER': 3071.0,
    #     'MRI_LOWER': 0.0,
    #     'MRI_UPPER': 1357.0,
    #     'anatomical_region': 'TH',
    #     'checkpoint_dir': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-llf-TH/epoch_700',
    #     'config_path': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_5.yaml',
    #     'data_path': '/media/prajbori/sda/private/dataset/proj_synthrad/training/synthRAD2025_Task1_Train_ABCD/Task1/TH',
    #     'mode': 'gaussian',
    #     'overlap': 0.2,
    #     'padding_mode': 'circular',
    #     'sampling_quality': 'fast',
    #     'sigma_scale': 0.125,
    #     'exp_name': '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/outputs_exp/llf-TH-13-padding',
    #     'max_cases': 15,
    # },
]

# Derive u2lf TH experiments from llf TH with modified paths
list_exp_u2lf_TH = []
for _exp in list_exp_llf_TH:
    _new = _exp.copy()
    _new['checkpoint_dir'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/some_checkpoints/apex-dist3-u2lf-TH/epoch_700'
    _new['config_path'] = '/media/prajbori/sda/private/github/proj_synthrad/algorithm-template/exp_configs/test_3090_6.yaml'
    if 'exp_name' in _new and isinstance(_new['exp_name'], str):
        _new['exp_name'] = _new['exp_name'].replace('/llf-TH-', '/u2lf-TH-')
    list_exp_u2lf_TH.append(_new)